baseURL = 'https://ofuro.me/'

languageCode = 'en-us'
title = "Yue's Notes"
theme = 'hugo-PaperMod'


[params.homeInfoParams]
Title = "Stay ðŸ˜Ž. Be ðŸ˜Š. Keep ðŸ“š"
Content = 'ãŠãµã‚ðŸ› => Bathe in the sea of knowledge.'

[[params.socialIcons]]
name = "github"
url = "https://github.com/helloboyxxx"

[[params.socialIcons]]
name = "email"
url = "mailto:yuec12@illinois.edu"

[[menu.main]]
name = "About Me"
url = "about"
weight = 7

[[menu.main]]
name = "Archive"
url = "archives"
weight = 8

[[menu.main]]
name = "Search"
url = "search/"
weight = 9

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10


[outputs]
home = [ "HTML", "RSS", "JSON" ]


[params]
ShowCodeCopyButtons = true


[markup.goldmark.renderer]
unsafe= true
