baseURL = 'https://ohuro.me/'

languageCode = 'en-us'
title = "Sam's Meanderings"
theme = 'PaperMod'


[params.homeInfoParams]
Title = "Stay ðŸ˜Ž. Be ðŸ˜Š. Keep ðŸ“š"
Content = 'ãŠãµã‚ðŸ› => Bathing in the ocean of knowledge'

[[params.socialIcons]]
name = "github"
url = "https://github.com/helloboyxxx"

[[params.socialIcons]]
name = "email"
url = "mailto:yuec12@illinois.edu"

[[menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10


[outputs]
home = [ "HTML", "RSS", "JSON" ]


[params]
ShowCodeCopyButtons = true


[markup.goldmark.renderer]
unsafe= true
